package oton.trainerhive;

import com.formdev.flatlaf.FlatDarkLaf;

/**
 *
 * @author Kailuss
 */
public class Main extends javax.swing.JFrame {

    // Creates new form Main
    public Main() {
	initComponents();
	// Centra la ventana
	this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuTrainerHive = new javax.swing.JMenu();
        jMenuArchivo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setName("frameMain"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(960, 600));

        jMenuBarMain.setBorder(null);

        jMenuTrainerHive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TrainerHiveLogo16.png"))); // NOI18N
        jMenuTrainerHive.setText("Trainer Hive");
        jMenuTrainerHive.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBarMain.add(jMenuTrainerHive);

        jMenuArchivo.setText("Archivo");
        jMenuBarMain.add(jMenuArchivo);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	// Establece FlatLaf Dark como el tema de la aplicación
	try {
	    javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Main().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuTrainerHive;
    // End of variables declaration//GEN-END:variables
}
